// Predefined areas of interest for participants
export const AREAS_OF_INTEREST = [
  "Competitive Programming",
  "Web Development",
  "Mobile App Development",
  "Machine Learning & AI",
  "Data Science",
  "Cybersecurity",
  "Cloud Computing",
  "Robotics",
  "IoT",
  "Game Development",
  "UI/UX Design",
  "Open Source",
  "Music",
  "Dance",
  "Drama & Theatre",
  "Art & Design",
  "Photography",
  "Literature",
  "Debating & Quiz",
  "Sports & Fitness",
  "Entrepreneurship",
  "Finance & Trading",
  "Social Events",
  "Environment",
];
