// Predefined areas of interest for participants
export const AREAS_OF_INTEREST = [
  "Technology",
  "Coding",
  "Web Development",
  "App Development",
  "AI/ML",
  "Cybersecurity",
  "Robotics",
  "Gaming",
  "E-Sports",
  "Music",
  "Dance",
  "Drama",
  "Art & Design",
  "Photography",
  "Literature",
  "Debating",
  "Quiz",
  "Sports",
  "Entrepreneurship",
  "Finance",
  "Marketing",
  "Social Work",
  "Environment",
];
