import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { adminService } from "../../services";
import { toast } from "react-toastify";
import { Box, Card, Flex, Text, Button, Heading, TextField, TextArea, Callout, Select } from "@radix-ui/themes";
import { ArrowLeftIcon, PersonIcon, EnvelopeClosedIcon, ImageIcon, FileTextIcon, CheckCircledIcon, CopyIcon, InfoCircledIcon } from "@radix-ui/react-icons";

const categories = [
  { value: "club", label: "Club" },
  { value: "council", label: "Council" },
  { value: "fest-team", label: "Fest Team" },
  { value: "other", label: "Other" },
];

const CreateOrganizer = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [credentials, setCredentials] = useState(null);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    description: "",
    logo: "",
    category: "club",
  });
  const [errors, setErrors] = useState({});

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (errors[name]) {
      setErrors((prev) => ({ ...prev, [name]: "" }));
    }
  };

  const validate = () => {
    const newErrors = {};

    if (!formData.name.trim()) {
      newErrors.name = "Organization name is required";
    }

    if (!formData.email.trim()) {
      newErrors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = "Invalid email format";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validate()) return;

    setLoading(true);
    try {
      const response = await adminService.createOrganizer({
        name: formData.name,
        email: formData.email,
        description: formData.description,
        logo: formData.logo,
        category: formData.category,
      });

      // Backend auto-generates password and returns credentials
      setCredentials(response.credentials);
      toast.success("Organizer created successfully!");
    } catch (error) {
      toast.error(error.response?.data?.message || "Failed to create organizer");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = async (text, label) => {
    try {
      await navigator.clipboard.writeText(text);
      toast.success(`${label} copied to clipboard`);
    } catch {
      window.prompt(`Copy the ${label}:`, text);
    }
  };

  // After creation — show credentials
  if (credentials) {
    return (
      <Box p="6">
        <Box style={{ maxWidth: "672px", margin: "0 auto" }}>
          <Flex direction="column" align="center" mb="6">
            <Flex
              align="center"
              justify="center"
              style={{
                width: "64px",
                height: "64px",
                backgroundColor: "var(--green-3)",
                borderRadius: "50%",
              }}
              mb="4"
            >
              <CheckCircledIcon width="32" height="32" color="var(--green-9)" />
            </Flex>
            <Heading size="6" mb="1">Organizer Created!</Heading>
            <Text color="gray">Share the login credentials below with the organizer</Text>
          </Flex>

          <Card size="3" mb="4">
            <Flex direction="column" gap="4">
              <Callout.Root color="blue">
                <Callout.Icon>
                  <InfoCircledIcon />
                </Callout.Icon>
                <Callout.Text>
                  The password was auto-generated by the system. Please copy and share these
                  credentials with the organizer — the password cannot be retrieved later.
                </Callout.Text>
              </Callout.Root>

              <Box>
                <Text as="label" size="2" weight="medium" mb="1" style={{ display: "block" }}>Login Email</Text>
                <Flex gap="2" align="center">
                  <TextField.Root
                    value={credentials.email}
                    readOnly
                    style={{ flex: 1 }}
                  />
                  <Button
                    type="button"
                    variant="soft"
                    onClick={() => copyToClipboard(credentials.email, "Email")}
                    title="Copy email"
                  >
                    <CopyIcon width="16" height="16" />
                  </Button>
                </Flex>
              </Box>

              <Box>
                <Text as="label" size="2" weight="medium" mb="1" style={{ display: "block" }}>Auto-Generated Password</Text>
                <Flex gap="2" align="center">
                  <TextField.Root
                    value={credentials.password}
                    readOnly
                    style={{ flex: 1, fontFamily: "monospace" }}
                  />
                  <Button
                    type="button"
                    variant="soft"
                    onClick={() => copyToClipboard(credentials.password, "Password")}
                    title="Copy password"
                  >
                    <CopyIcon width="16" height="16" />
                  </Button>
                </Flex>
              </Box>

              <Box>
                <Button
                  type="button"
                  variant="soft"
                  style={{ width: "100%" }}
                  onClick={() =>
                    copyToClipboard(
                      `Email: ${credentials.email}\nPassword: ${credentials.password}`,
                      "Credentials"
                    )
                  }
                >
                  <CopyIcon width="16" height="16" />
                  Copy Both Credentials
                </Button>
              </Box>
            </Flex>
          </Card>

          <Flex gap="4">
            <Button
              variant="soft"
              style={{ flex: 1 }}
              onClick={() => {
                setCredentials(null);
                setFormData({ name: "", email: "", description: "", logo: "", category: "club" });
              }}
            >
              Create Another
            </Button>
            <Button
              style={{ flex: 1 }}
              onClick={() => navigate("/admin/organizers")}
            >
              Go to Manage Organizers
            </Button>
          </Flex>
        </Box>
      </Box>
    );
  }

  return (
    <Box p="6">
      {/* Header */}
      <Button variant="ghost" onClick={() => navigate(-1)} mb="6">
        <ArrowLeftIcon width="16" height="16" />
        <Text>Back</Text>
      </Button>

      <Box style={{ maxWidth: "672px", margin: "0 auto" }}>
        <Flex direction="column" align="center" mb="6">
          <Flex
            align="center"
            justify="center"
            style={{
              width: "64px",
              height: "64px",
              backgroundColor: "var(--purple-3)",
              borderRadius: "50%",
            }}
            mb="4"
          >
            <PersonIcon width="32" height="32" color="var(--purple-9)" />
          </Flex>
          <Heading size="6" mb="1">Create New Organizer</Heading>
          <Text color="gray">Add a new club or organization to the platform</Text>
        </Flex>

        <Card size="3">
          <form onSubmit={handleSubmit}>
            <Flex direction="column" gap="5">
              <Callout.Root color="blue">
                <Callout.Icon>
                  <InfoCircledIcon />
                </Callout.Icon>
                <Callout.Text>
                  The system will auto-generate a secure login password. You will see the
                  credentials after creation so you can share them with the organizer.
                </Callout.Text>
              </Callout.Root>

              {/* Organization Name */}
              <Box>
                <Flex align="center" gap="1" mb="2">
                  <PersonIcon width="14" height="14" />
                  <Text as="label" size="2" weight="medium">Organization Name *</Text>
                </Flex>
                <TextField.Root
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="e.g., IIIT Hyderabad Programming Club"
                  color={errors.name ? "red" : undefined}
                />
                {errors.name && <Text size="1" color="red" mt="1">{errors.name}</Text>}
              </Box>

              {/* Email */}
              <Box>
                <Flex align="center" gap="1" mb="2">
                  <EnvelopeClosedIcon width="14" height="14" />
                  <Text as="label" size="2" weight="medium">Login Email *</Text>
                </Flex>
                <TextField.Root
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="organizer@example.com"
                  color={errors.email ? "red" : undefined}
                />
                {errors.email && <Text size="1" color="red" mt="1">{errors.email}</Text>}
              </Box>

              {/* Category */}
              <Box>
                <Text as="label" size="2" weight="medium" mb="2" style={{ display: "block" }}>Category</Text>
                <Select.Root
                  value={formData.category}
                  onValueChange={(value) => setFormData((prev) => ({ ...prev, category: value }))}
                >
                  <Select.Trigger style={{ width: "100%" }} />
                  <Select.Content>
                    {categories.map((cat) => (
                      <Select.Item key={cat.value} value={cat.value}>{cat.label}</Select.Item>
                    ))}
                  </Select.Content>
                </Select.Root>
              </Box>

              {/* Description */}
              <Box>
                <Flex align="center" gap="1" mb="2">
                  <FileTextIcon width="14" height="14" />
                  <Text as="label" size="2" weight="medium">Description</Text>
                </Flex>
                <TextArea
                  name="description"
                  value={formData.description}
                  onChange={handleChange}
                  rows={3}
                  placeholder="Brief description of the organization..."
                />
              </Box>

              {/* Logo URL */}
              <Box>
                <Flex align="center" gap="1" mb="2">
                  <ImageIcon width="14" height="14" />
                  <Text as="label" size="2" weight="medium">Logo URL</Text>
                </Flex>
                <TextField.Root
                  type="url"
                  name="logo"
                  value={formData.logo}
                  onChange={handleChange}
                  placeholder="https://example.com/logo.png"
                />
                <Text size="1" color="gray" mt="1">
                  Enter a URL to the organization's logo image
                </Text>
              </Box>

              {/* Preview */}
              {formData.logo && (
                <Card variant="surface">
                  <Text size="2" color="gray" mb="2">Logo Preview:</Text>
                  <img
                    src={formData.logo}
                    alt="Logo preview"
                    style={{ height: "64px", objectFit: "contain" }}
                    onError={(e) => (e.target.style.display = "none")}
                  />
                </Card>
              )}

              {/* Buttons */}
              <Flex gap="4" pt="4">
                <Button
                  type="button"
                  variant="soft"
                  onClick={() => navigate(-1)}
                  style={{ flex: 1 }}
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={loading}
                  style={{ flex: 1 }}
                >
                  {loading ? "Creating..." : "Create Organizer"}
                </Button>
              </Flex>
            </Flex>
          </form>
        </Card>
      </Box>
    </Box>
  );
};

export default CreateOrganizer;
